---
include:
  - board: nice_nano@2.0.0//zmk
    shield: charybdis_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: charybdis-left-split
  - board: nice_nano@2.0.0//zmk
    shield: charybdis_right
    artifact-name: charybdis-right-split
  - board: nice_nano@2.0.0//zmk
    shield: charybdis_right
    snippet: zmk-usb-logging charybdis-usb-test
    artifact-name: charybdis-right-USB-TEST
  - board: nice_nano@2.0.0//zmk
    shield: charybdis_left
    snippet: zmk-usb-logging
    artifact-name: charybdis-left-split-LOG
  - board: nice_nano@2.0.0//zmk
    shield: charybdis_right
    snippet: zmk-usb-logging charybdis-usb-test charybdis-sensor-probe
    artifact-name: charybdis-right-USB-DIAG2
  - board: nice_nano@2.0.0//zmk
    shield: charybdis_right
    snippet: zmk-usb-logging charybdis-sensor-debug
    artifact-name: charybdis-right-split-LOG
  - board: nice_nano@2.0.0//zmk
    shield: settings_reset
    artifact-name: settings-reset-ONLY-IF-NEEDED
